### ISSUE TITLE
I receive the message no_eligible_osu_files most of the time

### ISSUE THREAD

**Issue by RobertBTheDuck** [adlerosn/osu2ragna#1]
I've tried using osu2ragna on 2 different Windows PCs - both via Power Shell and via Windows cmd as well as through WSL (Ubuntu.)   

I have checked that ffmpeg is in my path.  Regardless of what I do almost every time I receive the error <song id>;no_eligible_osu_files in the borked.txt file.  

One example is - 23331;no_eligible_osu_files

I'm running Python 3.10.9 on Windows 10.  

My ffmpeg version is 2022-12-04

If you need any other output let me know and I'll get it right over to you.

**Comment by adlerosn** [comment]
Because that's a beatmapset that only contains osu!standard beatmaps.
My code only converts osu!mania 4k beatmaps.
Sorry for leaving that undocumented in the readme. I just copy-pasted osu2saber and refactored the code.
